opentelemetry-java-instrumentation/instrumentation/lettuce/lettuce-5.1/library/src/main/java/io/opentelemetry/instrumentation/lettuce/v5_1/OpenTelemetryTracing.java
[enhancement] Ignore the correct HGET spans in Lettuce5 (issue #16)
=> [enhancement] Ignore the correct HGET spans in Lettuce5 (issue #16)

README.md, README_CN.md
=> Add a link to the OzHera user manual on the OzHera homepage #25

opentelemetry-java-instrumentation/instrumentation/lettuce/lettuce-5.1/library/src/main/java/io/opentelemetry/instrumentation/lettuce/v5_1/OpenTelemetryTracing.java
[enhancement] Ignore the correct (HGET MGET MSET HMGET HGETALL) spans in Lettuce5 (close #16)
=>  [enhancement] Ignore the correct (HGET MGET MSET HMGET HGETALL) spans in Lettuce5 (issue #16)

trace-etl/trace-etl-manager/README.md, trace-etl/trace-etl-manager/README_CN.md, trace-etl/trace-etl-nginx/README.md, trace-etl/trace-etl-nginx/README_CN.md
[documentation] The trace-etl project needs to add an English readme. (close #31)
=>  [documentation] The trace-etl project needs to add an English readme. (close #31)

ozhera-log/log-agent-server/src/main/java/com/xiaomi/mone/log/server/service/DefaultLogProcessCollector.java, ozhera-log/log-agent/Dockerfile, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-common/src/test/java/com/xiaomi/mone/log/common/LineMessage.java, ozhera-log/log-manager/Dockerfile, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-stream/Dockerfile, ozhera-log/log-stream/pom.xml, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/common/util/StreamUtils.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/JobManager.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/extension/impl/RocketMqSinkJob.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/extension/impl/RocketMqSinkJobProvider.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/plugin/mq/rocketmq/RocketmqPlugin.java, ozhera-log/log-stream/src/main/resources/config/open.properties, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/log-manager/ozhera_log_manager.yml, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/log-stream/ozhera_log_stream.yml
Some unreasonable places have been repaired
close #27
=> Fix some bugs, optimize some judgments and update operator (issue #27)

opentelemetry-java-instrumentation/build.gradle, opentelemetry-java-instrumentation/buildSrc/src/main/kotlin/otel.publish-conventions.gradle.kts
Compilation error issue with opentelemetry-java-instrumentation resolve #41
=> resolve Compilation error issue with opentelemetry-java-instrumentation

opentelemetry-java-instrumentation/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/db/RedisCommandUtil.java, opentelemetry-java-instrumentation/instrumentation/jedis/jedis-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v1_4/JedisConnectionInstrumentation.java, opentelemetry-java-instrumentation/instrumentation/jedis/jedis-3.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v3_0/JedisConnectionInstrumentation.java, opentelemetry-java-instrumentation/instrumentation/lettuce/lettuce-5.1/library/src/main/java/io/opentelemetry/instrumentation/lettuce/v5_1/OpenTelemetryTracing.java
Filtering certain commands in Jedis, just like in Lettuce. resolve #48
=> resolve Filtering certain commands in Jedis, just like in Lettuce

opentelemetry-java-instrumentation/instrumentation/lettuce/lettuce-5.1/library/src/main/java/io/opentelemetry/instrumentation/lettuce/v5_1/OpenTelemetryTracing.java, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/trace-etl-server/ozhera_trace_etl_server.yml, trace-etl/trace-etl-server/pom.xml
Update opentelemetry and operator images resolve #50
=> Update opentelemetry and operator images

.github/workflows/ozhera-app-package.yml, .github/workflows/ozhera-demo-client-package.yml, .github/workflows/ozhera-demo-server-package.yml, .github/workflows/ozhera-log-package.yml, .github/workflows/ozhera-monitor-package.yml, .github/workflows/ozhera-operator-package.yml, .github/workflows/ozhera-prometheus-agent-package.yml, .github/workflows/ozhera-tspandata-package.yml, .github/workflows/ozhera-webhook-package.yml, .github/workflows/prometheus-starter-all-package.yml, .github/workflows/trace-etl-package.yml
=> [enhancement] Use github action for code inspection

ozhera-log/log-agent-server/pom.xml, ozhera-log/log-agent/src/main/resources/agent_channel_config.json
=> add config to enable json type (#59)

opentelemetry-java-instrumentation/dependencyManagement/dependencyManagement.gradle.kts, opentelemetry-java-instrumentation/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java
=> set JVM to ENV

readme/optimization/metrics-optimization.md, readme/optimization/metrics-optimization_cn.md
Modified Markdown Header Levels fix #65
=> Modified Markdown Header Levels

ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/common/HashUtil.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/export/impl/RmqExporter.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/JsonLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/LogParserFactory.java, ozhera-log/log-common/src/test/java/com/xiaomi/mone/log/common/LogParserFactoryTest.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/common/utils/ManagerUtil.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogConfigNacosServiceImpl.java
#68  added information about OPENTELEMETRY_ TYPE type logs can be sent according to the specified queue. Delimiter parsing is added to the configuration list
=> add rocketmq partition and raw log parse

ozhera-prometheus-agent/ozhera-prometheus-agent-server/src/main/java/com/xiaomi/youpin/prometheus/agent/config/CacheConfiguration.java
=> Bugfix dingding

ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/common/AbstractElementAdapter.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/export/MsgExporter.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/RmqExporter.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/RmqOutput.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/RocketMQService.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/service/OutPutService.java, ozhera-log/log-agent/src/test/java/com/xiaomi/mone/log/agent/Comparator.java, ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/enums/MiddlewareEnum.java
=> update log-agent extension

ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppAlarmService.java
=> fix bug alarm edit single at member

ozhera-app/app-common/src/main/java/com/xiaomi/mone/app/common/Constant.java, ozhera-app/app-common/src/main/java/com/xiaomi/mone/app/model/vo/PodInfo.java, ozhera-app/app-common/src/main/java/com/xiaomi/mone/app/model/vo/TpcLabelRes.java, ozhera-app/app-common/src/main/java/com/xiaomi/mone/app/model/vo/TpcPageRes.java, ozhera-app/app-server/Dockerfile, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/env/DefaultEnvIpFetch.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/env/DefaultHttpEnvIpFetch.java
=> feat:update app get env info

readme/contributing/contributing.md, readme/contributing/contributing_cn.md
=> update contributing image location

ozhera-log/log-agent-server/pom.xml, ozhera-log/log-agent-server/src/main/java/com/xiaomi/mone/log/server/LogAgentServerBootstrap.java, ozhera-log/log-agent-server/src/main/java/com/xiaomi/mone/log/server/common/ServerConstant.java, ozhera-log/log-agent-server/src/main/java/com/xiaomi/mone/log/server/porcessor/PingProcessor.java, ozhera-log/log-agent-server/src/main/java/com/xiaomi/mone/log/server/service/ApplicationShutdownHook.java, ozhera-log/log-agent/pom.xml, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/AbstractChannelService.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelDefine.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelEngine.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/WildcardChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/listener/DefaultFileMonitorListener.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/locator/ChannelDefineRpcLocator.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/wilcard/WildcardChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/common/ChannelUtil.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/rpc/processor/LogProcessor.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/rpc/task/PingTask.java, ozhera-log/log-agent/src/main/resources/agent_channel_config.json, ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/enums/LogTypeEnum.java, ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/model/meta/LogCollectMeta.java, ozhera-log/log-common/pom.xml, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/common/Constant.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/common/PathUtils.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/JsonLogParser.java, ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/common/utils/ManagerUtil.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/domain/Tpc.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/store/DefaultStoreExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/pom.xml
=> Feature wildcard file monitor

ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/HeraDashboardService.java
=> refactor_change_name

trace-etl/trace-etl-es/pom.xml, trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/queue/impl/RocksdbStoreServiceImpl.java
The pv storage of trace-etl-es has not been fully recycled resolve #86
=> resolve The pv storage of trace-etl-es has not been fully recycled

ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/dao/HeraProjectGroupUserDao.java, ozhera-log/log-manager/Dockerfile, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogSpaceServiceImpl.java, ozhera-log/log-manager/src/main/resources/mapper/MilogLogSearchSaveMapper.xml
=> update valid list

ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/mq/RocketMqHeraMetaDataConsumer.java
fix sql getOne return many result exception resolve #123
=> fix sql getOne return many result exception

ozhera-app/app-server/src/test/java/com/xiaomi/mone/test/HeraMetaDataTest.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/redis/RedisService.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/mq/RocketMqHeraMetaDataConsumer.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/util/HeraMetaDataConvertUtil.java
fix repeated insertion meta data problem resolve #130
=> fix repeated insertion meta data problem

ozhera-app/app-server/Dockerfile, ozhera-app/app-server/src/main/java/com/xiaomi/mone/app/controller/AppController.java, ozhera-app/app-server/src/main/java/com/xiaomi/mone/app/controller/HeraAppEnvController.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/HeraAppEnvService.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/env/DefaultEnvIpFetch.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/impl/HeraAppEnvServiceImpl.java, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/hera-app/ozhera_app.yml
#134 
Support HTTP to query IP list information and make hera app a service
=> feat:hera app supported query no probe ips

ozhera-monitor/ozhera-monitor-common/src/main/java/com/xiaomi/mone/monitor/DashboardConstant.java, ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/HeraDashboardService.java, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/heraSLA.ftl, ozhera-prometheus-agent/ozhera-prometheus-agent-client/src/main/java/com/xiaomi/youpin/prometheus/agent/alertManagerClient/AlertManagerClient.java, ozhera-prometheus-agent/ozhera-prometheus-agent-common/src/main/java/com/xiaomi/youpin/prometheus/agent/result/alertManager/Labels.java, ozhera-prometheus-agent/ozhera-prometheus-agent-common/src/main/java/com/xiaomi/youpin/prometheus/agent/util/DateUtil.java, ozhera-prometheus-agent/ozhera-prometheus-agent-common/src/test/java/com/xiaomi/youpin/prometheus/agent/test/TimeTest.java, ozhera-prometheus-agent/ozhera-prometheus-agent-server/src/test/java/com/xiaomi/youpin/prometheus/agent/test/feishuTest.java, ozhera-prometheus-agent/ozhera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/DingDingService.java, ozhera-prometheus-agent/ozhera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/alarmContact/BaseAlertContact.java, ozhera-prometheus-agent/ozhera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/alarmContact/DingAlertContact.java, ozhera-prometheus-agent/ozhera-prometheus-agent-service/src/main/resources/dingding/dingdingbasicCart.ftl
=> Feature hera sla

ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/AbstractLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/CustomLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/FieldInterceptor.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/JsonLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/LogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/NginxLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/RawLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/RegexLogParser.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/SeparatorLogParser.java
#152 
Added interface for log processing
=> Add post processing service for log content

.github/workflows/ozhera-operator-package.yml, ozhera-operator/ozhera-operator-common/pom.xml, ozhera-operator/ozhera-operator-server/Dockerfile, ozhera-operator/ozhera-operator-server/pom.xml, ozhera-operator/ozhera-operator-service/pom.xml, ozhera-operator/ozhera-operator-service/src/main/java/run/mone/hera/operator/service/HeraBootstrapInitService.java, ozhera-operator/pom.xml
=> upgrade operator jdk21

.github/workflows/prometheus-starter-all-package.yml, ozhera-demo-client/ozhera-demo-client-server/pom.xml, prometheus-starter-all/pom.xml, prometheus-starter-all/prometheus-diy-client/pom.xml, prometheus-starter-all/prometheus-diy-client/src/main/java/com/xiaomi/youpin/prometheus/all/client/Prometheus.java, prometheus-starter-all/prometheus-diy-starter/pom.xml
=> upgrade starter jdk21

.github/workflows/trace-etl-package.yml, trace-etl/pom.xml, trace-etl/trace-etl-api/pom.xml, trace-etl/trace-etl-common/pom.xml, trace-etl/trace-etl-dao/pom.xml, trace-etl/trace-etl-domain/pom.xml, trace-etl/trace-etl-es/dockerfile, trace-etl/trace-etl-es/pom.xml, trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/consumer/ConsumerService.java, trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/util/bloomfilter/TraceIdRedisBloomUtil.java, trace-etl/trace-etl-es/src/main/resources/config/opensource-outer.properties, trace-etl/trace-etl-extensions/pom.xml, trace-etl/trace-etl-extensions/trace-etl-rocketmq-extension/pom.xml, trace-etl/trace-etl-manager/dockerfile, trace-etl/trace-etl-manager/pom.xml, trace-etl/trace-etl-nginx/pom.xml, trace-etl/trace-etl-server/dockerfile, trace-etl/trace-etl-server/pom.xml, trace-etl/trace-etl-service/pom.xml
=> upgrade trace-etl jdk21

ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/bo/AlarmPresetMetrics.java
=> add alarm url config

ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/enums/ResourceEnum.java, ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/model/bo/MiLogResource.java, ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/model/vo/ResourceInfo.java, ozhera-log/log-api/src/main/java/com/xiaomi/mone/log/api/model/vo/ResourceUserSimple.java, ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/bootstrap/LogStoragePlugin.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/common/validation/ResourceValidation.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/model/pojo/MilogEsClusterDO.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/model/pojo/MilogMiddlewareConfig.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/model/vo/LogStoreParam.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/agent/MilogAgentServiceFactory.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/common/CommonExtensionServiceFactory.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/dictionary/DefaultDictionaryExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/dictionary/DictionaryExtensionServiceFactory.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/resource/DefaultResourceExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/resource/ResourceExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/resource/ResourceExtensionServiceFactory.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/store/StoreExtensionServiceFactory.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/tail/TailExtensionServiceFactory.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogConfigNacosServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogDictionaryServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogMiddlewareConfigServiceImpl.java, ozhera-log/log-stream/pom.xml, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/mysql/sql/hera.sql
#133 
resouce maanger supported doris or clickhouse datasource config
=> resouce manager and other resource

ozhera-log/log-agent-server/src/main/java/com/xiaomi/mone/log/server/service/DefaultAgentConfigAcquirer.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelEngine.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/WildcardChannelServiceImpl.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/common/PathUtils.java, ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/JsonLogParser.java, ozhera-log/log-common/src/test/java/com/xiaomi/mone/log/common/PathUtilsTest.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/EsDataServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogStoreServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogConfigNacosServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogMiddlewareConfigServiceImpl.java
=> fix bug and code optimize

ozhera-log/log-agent/pom.xml, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/KafkaExporter.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/KafkaMQService.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/KafkaOutput.java
=> feat: apply kafka

HEADER, LICENSE, ozhera-app/app-api/pom.xml, ozhera-app/app-common/pom.xml, ozhera-app/app-server/pom.xml, ozhera-app/app-service/pom.xml, ozhera-log/log-agent-server/pom.xml, ozhera-log/log-agent/pom.xml, ozhera-log/log-api/pom.xml, ozhera-log/log-common/pom.xml, ozhera-log/log-manager/pom.xml, ozhera-log/log-stream/pom.xml, ozhera-log/pom.xml, pom.xml
=> feat: maven project structure adjustment (#186)

ozhera-log/log-agent/pom.xml, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/WildcardChannelServiceImpl.java, ozhera-log/log-agent/src/main/resources/agent_channel_config.json, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/controller/MilogConfigController.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/domain/LogTail.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/EsDataServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogStoreServiceImpl.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/bootstrap/StreamAgent.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/config/ConfigManager.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/extension/kafka/KafkaConsumerRunner.java
#97
handling of progress issues in collecting wildcard files
=> refactor: update wildcard file coll

ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/env/DefaultNacosEnvIpFetch.java, ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/env/EnvIpFetch.java, ozhera-log/log-agent/Dockerfile, ozhera-log/log-agent/pom.xml, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/listener/DefaultFileMonitorListener.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/service/ServiceRegistryService.java, ozhera-log/log-agent/src/main/resources/config.properties, ozhera-log/log-agent/src/main/resources/config/dev.properties, ozhera-log/log-agent/src/main/resources/config/open.properties, ozhera-log/log-agent/src/test/java/com/xiaomi/mone/log/agent/DefaultFileMonitorListenerTest.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/bootstrap/MiLogStreamBootstrap.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/common/util/StreamUtils.java, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/nacos/config/hera_app_config_#_DEFAULT_GROUP.properties, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/sentinel/sentinbel-dashboard-ingress.yml, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/sentinel/sentinel-dashboard.yml
#204 
When the logging service is started, it will register itself in Nacos and add a hook to remove it from Nacos when the service is shut down. When obtaining its own IP list, some special processing has been done. Added deployment and ingress for sentinel dashboard
=> feat: log agent service registration and obtaining its service list

ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/model/prometheus/Metric.java, ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/prometheus/PrometheusService.java
https://github.com/XiaoMi/ozhera/issues/205
display http status code in metrics exception statistics page.
=> feat: display http status code in metrics exception statistics page

ozhera-app/app-service/src/main/java/com/xiaomi/mone/app/service/mq/model/HeraAppMessage.java
=> feat: ozhera app support config appLanguage by env

trace-etl/trace-etl-extensions/trace-etl-kafka-extension/src/main/java/run/mone/trace/etl/extension/kafka/KafkaExtension.java
feat: trace producer\consumer kafka message enable compress, type is lz4 #216
=> feat: trace producer\consumer kafka message enable compress, type is lz4

trace-etl/README.md, trace-etl/README_cn.md
feat: trace-etl add welcome page #233
=> feat: trace-etl add welcome page

trace-etl/trace-etl-dao/pom.xml
feat: update mariadb version to 3.1.4
=> feat: update mariadb version to 3.1.4

ozhera-log/log-agent-server/pom.xml, ozhera-log/log-agent/pom.xml, ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogMiddlewareConfigServiceImpl.java, ozhera-log/log-stream/pom.xml, ozhera-log/pom.xml, pom.xml
#240  
update log dependency version
=> refactor: update log dependency version

ozhera-demo-server/ozhera-demo-server-api/pom.xml, ozhera-demo-server/ozhera-demo-server-server/pom.xml, ozhera-demo-server/pom.xml, ozhera-webhook/ozhera-webhook-server/pom.xml, ozhera-webhook/pom.xml, pom.xml, prometheus-starter-all/pom.xml, prometheus-starter-all/prometheus-diy-client/pom.xml
feat: update dependency pom verison
=> feat: update dependency pom verison

ozhera-app/app-server/pom.xml, ozhera-app/pom.xml, ozhera-log/log-manager/pom.xml, ozhera-log/pom.xml, pom.xml
=> refactor: update version clean

ozhera-demo-client/pom.xml, ozhera-operator/pom.xml, ozhera-webhook/pom.xml, prometheus-starter-all/pom.xml, trace-etl/pom.xml
feat: update repeat pom dependency version
=> feat: update repeat pom dependency version

build.sh, docker-build.sh, ozhera-app/pom.xml, ozhera-monitor/Dockerfile
#263 
After one click construction, the project can be mirrored and pushed to a remote warehouse
=> feat:  add one click build project script

ozhera-log/log-agent-server/pom.xml, ozhera-log/log-agent/pom.xml, ozhera-log/log-api/pom.xml, ozhera-log/log-common/pom.xml, ozhera-log/log-manager/pom.xml, ozhera-log/log-stream/pom.xml, ozhera-log/pom.xml, pom.xml, trace-etl/pom.xml
=> refactor: update dependency version release

ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/utils/DateUtils.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/job/EsIndexJob.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/EsIndexOperateService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/EsIndexOperateServiceImpl.java, ozhera-log/log-manager/src/main/resources/config/open.properties
#274 
Support scrolling actual indexes by date and size
=> feat: supported es template update

ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/plugin/es/EsPlugin.java, ozhera-log/log-stream/src/test/java/com/xiaomi/mone/log/stream/EsPluginTest.java
build multiple process to use
#68
=> refactor: update es plugin processor multiple

ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/jaegerQuery.ftl, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraScrapeJobTemplate/dockerScrapeJob.ftl
=> fix: fix dashboard double number of hosts question

ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/extension/DefaultLogSendFilter.java
=> feat: fix log-stream data type conversion bug

ozhera-prometheus-agent/ozhera-prometheus-agent-client/src/main/java/com/xiaomi/youpin/prometheus/agent/prometheusClient/PrometheusVMClient.java
=> fix: vm cluster duplicate scrape job problem

ozhera-monitor/ozhera-monitor-common/src/main/java/com/xiaomi/mone/monitor/DashboardConstant.java, ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/HeraDashboardService.java, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/dubboConsumerMarket.ftl, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/dubboConsumerOverview.ftl, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/dubboProviderMarket.ftl, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/dubboProviderOverview.ftl, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/httpServerMarket.ftl, ozhera-monitor/ozhera-monitor-service/src/main/resources/heraGrafanaTemplate/httpServerOverview.ftl, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/nacos/config/mimonitor_open_config_#_DEFAULT_GROUP.properties, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/vmCluster/vm-k8s-yaml/vmAgent.yaml
=> feat: interface disk add env Filter box

ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/dao/MilogLogstoreDao.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/domain/TraceLog.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/common/CommonExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/common/DefaultCommonExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/EsDataServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogQueryServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogSpaceServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogStoreServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogConfigNacosServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogStreamServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/StreamPartitionServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/nacos/DynamicConfigPublisher.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/nacos/impl/SpaceConfigNacosPublisher.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/nacos/impl/StreamConfigNacosPublisher.java, ozhera-log/log-manager/src/test/java/com/xiaomi/mone/log/manager/dao/LogStoreDaoTest.java, ozhera-log/log-stream/pom.xml, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/common/LogStreamConstants.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/LogDataTransfer.java
=> refactor: log-manager update query log by trace and optimize

ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/nacos/config/ozhera_app_config_#_DEFAULT_GROUP.properties, ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/webhook/ozhera_webhook_server.yaml, ozhera-webhook/ozhera-webhook-server/pom.xml, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/Bootstrap.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/common/HttpClientUtil.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/common/K8sUtilBean.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/config/NacosConfiguration.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/controller/HealthController.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/controller/HeraWebhookController.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/k8s/Container.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/k8s/Limits.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/k8s/Requests.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/k8s/Resource.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/k8s/VolumeMount.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/tpc/TpcAppInfo.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/tpc/TpcAppRequest.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/domain/tpc/TpcEnvRequest.java, ozhera-webhook/ozhera-webhook-server/src/main/java/run/mone/hera/webhook/service/HeraWebhookService.java, ozhera-webhook/ozhera-webhook-server/src/main/resources/application.properties, ozhera-webhook/ozhera-webhook-server/src/main/resources/hera_init/webhook/hera_webhook_config.yaml, ozhera-webhook/pom.xml
=> feat: auto-inject-log-agent

ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/WildcardChannelServiceImpl.java
fix log agent holding last line for too long.
close #318
=> fix: log-agent holding last line for too long

ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/nacos/config/hera_trace_config_#_DEFAULT_GROUP.properties, trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/consumer/FilterService.java, trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/consumer/MetricsParseService.java
feat: trace-etl add degradation measures #324
=> feat: trace-etl add degradation measures

ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/domain/TraceLog.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogTailServiceImpl.java
#329 
fix Mismatched MQ Used When Creating Tail
=> fix: tail bind mq from store

README.md, README_CN.md, ozhera-app/app-server/Dockerfile, ozhera-demo-client/ozhera-demo-client-server/Dockerfile, ozhera-demo-server/ozhera-demo-server-server/Dockerfile, ozhera-operator/ozhera-operator-server/Dockerfile, ozhera-prometheus-agent/ozhera-prometheus-agent-server/Dockerfile, ozhera-webhook/ozhera-webhook-server/dockerfile
optimizing the ozhera homepage content resolved #342
=> feat: optimizing the ozhera homepage content

README.md
=> fix: update live demo url

ozhera-app/app-server/pom.xml, ozhera-app/pom.xml, ozhera-demo-client/pom.xml, ozhera-demo-server/pom.xml, ozhera-log/pom.xml, ozhera-monitor/pom.xml, ozhera-operator/pom.xml, ozhera-prometheus-agent/pom.xml, prometheus-starter-all/pom.xml, trace-etl/pom.xml
fix: Local Debug & Build needs no maven-gpg-plugin verification #341
=> fix: Local Debug & Build needs no maven-gpg-plugin verification #341

ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/model/prometheus/MetricDetailQuery.java
=> fix: delete unused annotation

ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/listener/DefaultFileMonitorListener.java, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/common/Version.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/dao/MilogAppMiddlewareRelDao.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/compensate/StreamCompensateTask.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/plugin/es/EsPlugin.java
=> feat: fix log-agent、log-manager bug

ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/controller/MilogConfigController.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/LogTailService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/tail/DefaultTailExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/tail/TailExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/common/LogStreamConstants.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/LogDataTransfer.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/extension/MessageLifecycleManager.java, ozhera-log/log-stream/src/main/java/com/xiaomi/mone/log/stream/job/extension/impl/DefaultMessageLifecycleManager.java
#355 
ehance the application environment information query function by introducing data center information to improve the traceability and management efficiency of log data. Additionally, pre- and post-processing logic is added to log-stream to ensure the completeness and accuracy of log data.
=> refactor: app env query and machineRoom and message handle pre and post

ozhera-log/log-common/src/main/java/com/xiaomi/mone/log/parse/JsonLogParser.java
=> refactor: update json parser

ozhera-log/log-manager/src/main/resources/logback.xml
#385 
logback configuration to separate regular logs and error logs into different files
=> refactor: add log Separate

ozhera-log/log-agent/pom.xml, ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/common/ExecutorUtil.java, ozhera-log/log-agent/src/test/java/com/xiaomi/mone/log/agent/common/ExecutorUtilTest.java
#396 
Log-agent scheduled thread factory uses coroutines
=> refactor: replace threads with coroutines and add names

ozhera-app/app-service/pom.xml, ozhera-log/pom.xml, ozhera-monitor/ozhera-monitor-service/pom.xml, ozhera-operator/pom.xml, ozhera-prometheus-agent/pom.xml, pom.xml, prometheus-starter-all/pom.xml, trace-etl/pom.xml
there are vulnerabilities in some older versions of JAR packages; upgrade to a higher version
=> refactor: upgrade jar package version

ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/LogSpaceServiceImpl.java
#399 
Adding a caching layer for querying all spaces to optimize user experience.
=> refactor: upgrade get all space

ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/MilogConfigNacosService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/common/CommonExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/common/DefaultCommonExtensionService.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogConfigNacosServiceImpl.java, ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/StreamPartitionServiceImpl.java
#405 
Simultaneous configuration overwrite issue when modifying multiple data centers
=> fix: fix multiple region read or write config bug

ozhera-monitor/ozhera-monitor-server/src/main/java/com/xiaomi/mone/monitor/config/RedisConfig.java, ozhera-monitor/ozhera-monitor-server/src/test/java/com/xiaomi/mone/monitor/FreeMarkerTest.java, ozhera-monitor/ozhera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/prometheus/PromQL.java, ozhera-monitor/ozhera-monitor-service/src/test/java/com/xiaomi/mone/monitor/test/TestUtils.java
=> fix: add header

.github/workflows/validate_pr_commits.yml, .gitmodules
move commit check action to submodule
=> fix: commit check action move to submodule

ozhera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogMiddlewareConfigServiceImpl.java
Associate issue:
fix https://github.com/apache/ozhera/issues/454 
refactor module:
ozhera-log
Changes made:
paginated query store list bug fixed
=> fix: The issue of storing pagination list queries is fixed

README.md, README_CN.md
change README and README_CN to ASF
=> refactor: change README and README_CN

ozhera-app/app-server/src/main/java/org/apache/ozhera/app/AppBootstrap.java, ozhera-app/app-server/src/main/java/org/apache/ozhera/app/aop/OperateAppBaseInfoAspect.java, ozhera-app/app-server/src/main/java/org/apache/ozhera/app/exception/AppExceptionControllerAdvice.java, ozhera-app/app-server/src/main/resources/application.properties, ozhera-demo-client/ozhera-demo-client-server/src/main/java/org/apache/ozhera/demo/client/bootstrap/HeraDemoClientBootstrap.java, ozhera-demo-client/ozhera-demo-client-service/pom.xml, ozhera-demo-client/ozhera-demo-client-service/src/main/java/org/apache/ozhera/demo/client/service/DubboHealthServiceImpl.java, ozhera-demo-server/ozhera-demo-server-server/src/main/java/org/apache/ozhera/demo/server/HeraDemoServerBootstrap.java, ozhera-intelligence/ozhera-intelligence-server/src/main/java/org/apache/ozhera/intelligence/bootstrap/IntelligenceBootStrap.java, ozhera-intelligence/pom.xml, ozhera-log/log-agent-server/src/main/java/org/apache/ozhera/log/server/LogAgentServerBootstrap.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/bootstrap/MiLogAgentBootstrap.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/AbstractChannelService.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/bootstrap/MiLogManagerBootstrap.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/bootstrap/MiLogStreamBootstrap.java, ozhera-monitor/ozhera-monitor-server/src/main/java/org/apache/ozhera/monitor/bootstrap/MiMonitorBootstrap.java, ozhera-operator/ozhera-operator-server/src/main/java/org/apache/ozhera/operator/HeraBootstrap.java, ozhera-prometheus-agent/ozhera-prometheus-agent-server/src/main/java/org/apache/ozhera/prometheus/agent/bootstrap/PrometheusAgentBootstrap.java, ozhera-webhook/ozhera-webhook-server/src/main/java/org/apache/ozhera/webhook/Bootstrap.java, pom.xml, prometheus-starter-all/prometheus-diy-starter/pom.xml, trace-etl/trace-etl-es/src/main/java/org/apache/ozhera/trace/etl/es/bootstrap/TraceEtlEsBootstrap.java, trace-etl/trace-etl-manager/src/main/java/org/apache/ozhera/trace/etl/manager/bootstrap/TraceEtlManagerBootstrap.java, trace-etl/trace-etl-nginx/src/main/java/org/apache/ozhera/trace/etl/nginx/bootstrap/TraceEtlNginxBootstrap.java, trace-etl/trace-etl-server/src/main/java/org/apache/ozhera/trace/etl/bootstrap/TraceEtlBootstrap.java
Associate issue:
fix https://github.com/apache/ozhera/issues/472
Changes made:
update the package path of the startup class
=> refactor: update the package path of the startup class

ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/memory/AgentMemoryServiceImpl.java, ozhera-log/log-agent/src/main/resources/log_impl_type.json, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/JsonLogParser.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/bind/LogTypeProcessorFactory.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/config/MilogConfigListener.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/job/JobManager.java, ozhera-monitor/ozhera-monitor-server/pom.xml, ozhera-monitor/ozhera-monitor-server/src/main/java/org/apache/ozhera/monitor/aop/HeraRequestMappingAspect.java, ozhera-monitor/ozhera-monitor-server/src/main/java/org/apache/ozhera/monitor/config/DataSourceConfig.java, ozhera-monitor/ozhera-monitor-server/src/main/resources/META-INF/spring.factories, ozhera-monitor/ozhera-monitor-service/src/main/resources/generatorConfig.xml, pom.xml
Associate issue:
fix https://github.com/apache/ozhera/issues/472
Changes made:
pgrade package name and code update
=> refactor: upgrade package name and code update

ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogSpaceServiceImpl.java
Associate issue:
fix https://github.com/apache/ozhera/issues/490
Changes moudle: hera-log
update space cache operate
=> refactor: update space cache

pom.xml
=> fix: update spring-context version

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/OIP.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build-pr-commit.yml, .github/workflows/ozhera-app-package.yml, .github/workflows/ozhera-demo-client-package.yml, .github/workflows/ozhera-demo-server-package.yml, .github/workflows/ozhera-intelligence-package.yml, .github/workflows/ozhera-log-package.yml, .github/workflows/ozhera-monitor-package.yml, .github/workflows/ozhera-operator-package.yml, .github/workflows/ozhera-prometheus-agent-package.yml, .github/workflows/ozhera-tspandata-package.yml, .github/workflows/ozhera-webhook-package.yml, .github/workflows/prometheus-starter-all-package.yml, .github/workflows/trace-etl-package.yml, .github/workflows/validate_pr_commits.yml, .github/workflows/validate_pr_title.yml, readme/best-practices/indexTemplate.sh
add a header to the file where the declaration is missing
fixes #474
=> fix: add a header to the file where the declaration is missing

ozhera-log/log-stream/src/main/resources/config.properties, ozhera-log/log-stream/src/main/resources/config/open.properties, ozhera-log/log-stream/src/main/resources/logback.xml, ozhera-monitor/ozhera-monitor-server/src/main/resources/META-INF/app.properties, ozhera-monitor/ozhera-monitor-server/src/main/resources/META-INF/spring.factories, ozhera-monitor/ozhera-monitor-service/src/main/resources/sql/create_table.sql, trace-etl/trace-etl-manager/dockerfile
add header to files missing copyright notice
fixes #474
=> fix: add header to files missing copyright notice

ozhera-log/log-api/src/main/java/org/apache/ozhera/log/api/model/dto/LogFilterOptions.java, ozhera-log/log-api/src/main/java/org/apache/ozhera/log/api/model/dto/LogUrlParam.java, ozhera-log/log-api/src/main/java/org/apache/ozhera/log/api/service/HeraLogApiService.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/HeraLogApiServiceImpl.java
https://github.com/apache/ozhera/issues/527
https://github.com/apache/ozhera/issues/527
=> feat: offer HeraLogApiService service

.github/workflows/validate_pr_commits.yml
=> feat: change submission information verification process

ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/service/api/impl/GrafanaServiceExtensionImpl.java, ozhera-prometheus-agent/ozhera-prometheus-agent-common/src/main/java/org/apache/ozhera/prometheus/agent/util/Http.java, ozhera-prometheus-agent/ozhera-prometheus-agent-service/src/main/java/org/apache/ozhera/prometheus/agent/service/api/impl/PrometheusIpServiceExtensionImpl.java, trace-etl/trace-etl-server/src/main/java/org/apache/ozhera/trace/etl/util/prometheus/HTTPServer.java
relates to https://github.com/apache/ozhera/discussions/532
=> fix: refactor code to get last line from response

.asf.yaml
Labels must be lowercase alphanumerical and <= 35 characters!
fixes #475 
Not applicable.
Not applicable.
Not applicable.
=> refactor: update the labels to comply with the standards.

ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/bo/LogTailParam.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/dto/LogTailDTO.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/pojo/MilogLogTailDo.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/vo/QuickQueryVO.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-manager/src/main/resources/log.sql
add `origin_system` field to logtail
fixs #542
=> feat: add origin_system to logtail to identify third-party plaform

ozhera-log/log-common/src/main/java/org/apache/ozhera/log/model/SinkConfig.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/AbstractLogParser.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/LogParserData.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/LogParserFactory.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/SeparatorLogParser.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/utils/IndexUtils.java, ozhera-log/log-common/src/test/java/org/apache/ozhera/log/common/IndexUtilsTest.java, ozhera-log/log-common/src/test/java/org/apache/ozhera/log/common/LogParserFactoryTest.java, ozhera-log/log-common/src/test/java/org/apache/ozhera/log/common/LogParserTest.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/job/TailLogCountJob.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/AgentConfigServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogCountServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/MilogConfigNacosServiceImpl.java, ozhera-log/log-manager/src/main/resources/mapper/MilogLogstailMapper.xml, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/config/ConfigManager.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/job/JobManager.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/job/SinkJobConfig.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/job/extension/impl/DefaultStreamCommonExtension.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/job/extension/kafka/KafkaSinkJobProvider.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/job/extension/rocketmq/RocketMqSinkJobProvider.java, ozhera-log/log-stream/src/test/java/org/apache/ozhera/log/stream/TestSomething.java
enhancement to our log parsing and statistics functionality to improve the efficiency and flexibility of log processing
https://github.com/apache/ozhera/issues/547
=> feat: optimize log parsing and statistics functions

ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/AbstractLogParser.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/RegexLogParser.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/SeparatorLogParser.java, ozhera-log/log-common/src/test/java/org/apache/ozhera/log/common/LogParserTest.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-stream/src/main/java/org/apache/ozhera/log/stream/plugin/es/EsPlugin.java
-The AbstractLogParser has added valueMap and parseKeyValueList methods for processing key value pairs
-RegexLogParser inherits the abstract log parser and implements specific regular parsing logic
-SeparatorLogParser inherits the abstract log parser and implements specific delimiter parsing logic
-Optimized log parsing performance, especially for parsing large amounts of log data
-Adjusted test cases to adapt to the new parsing logic
https://github.com/apache/ozhera/issues/547
=> refactor: fefactoring log parsing logic

NOTICE
=> fix: add 2025 to NOTICE

pom.xml
upgrade excel dependency version #554
=> feat: upgrade excel dependency version

ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/AbstractChannelService.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelEngine.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelServiceFactory.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelServiceImpl.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/utils/ConfigUtils.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/EsDataServiceImpl.java
-Add ChannelServiceFactory class to create different types of ChannelServices
-Optimize log filtering logic and move it to ChannelServiceImpl
-Refactoring the configuration acquisition method and adding support for default values
-Optimize code structure, improve readability and maintainability
https://github.com/apache/ozhera/issues/547
=> refactor: refactor channelService creation logic

ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelEngine.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/comparator/LogLevelSimilarComparator.java
- Resolve the problem that the configuration information received by tail is not updated
Resolve the problem that the configuration information received by log-agent is not updated.
None.
Just simple modifications, no test cases required.
Verify by viewing logs.
None.
=> fix:  resolve the tail update problem in log-agent

ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogCountServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogTailServiceImpl.java
-Optimize log statistics logic to improve processing efficiency - remove unnecessary template existence checks
-Simplify code structure and improve readability
-Fix some potential bugs and performance issues
=> refactor: refactoring log statistics function

ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/LogParserFactory.java, ozhera-log/log-common/src/main/java/org/apache/ozhera/log/parse/PlaceholderParser.java, ozhera-log/log-common/src/test/java/org/apache/ozhera/log/common/LogParserTest.java
Added placeholder parsing functionality in the log parsing module to extract structured data from logs.
https://github.com/apache/ozhera/issues/578
=> feat: Add placeholder parsing function

ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/bo/AlarmRuleType.java, ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/bo/AlarmStrategyType.java, ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/service/api/AppAlarmServiceExtension.java, ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/service/api/impl/AppAlarmServiceExtensionImpl.java, ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/service/impl/AlarmStrategyServiceImpl.java, ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/service/impl/AppAlarmServiceImpl.java, ozhera-monitor/ozhera-monitor-service/src/main/java/org/apache/ozhera/monitor/service/model/prometheus/AlarmRuleRequest.java
Expanded business metric alarm
=> feat: extended business alarm

ozhera-intelligence/ozhera-intelligence-service/src/main/java/org/apache/ozhera/intelligence/agents/config/AgentConfig.java, ozhera-intelligence/ozhera-intelligence-service/src/main/java/org/apache/ozhera/intelligence/service/TraceAnalysisService.java
=> feat: add new message type and optimize prompt logic (#584)

ozhera-log/log-agent-server/pom.xml, ozhera-log/log-agent-server/src/main/java/org/apache/ozhera/log/server/service/DefaultLogProcessCollector.java, ozhera-log/log-agent-server/src/main/java/org/apache/ozhera/log/server/service/DefaultPublishConfigService.java, ozhera-log/log-agent/pom.xml, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/AbstractChannelService.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelEngine.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelServiceFactory.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/ChannelState.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/channel/listener/DefaultFileMonitorListener.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/extension/KafkaService.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/extension/RocketMQService.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/rpc/processor/LogProcessor.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/rpc/processor/NodeCollInfoProcessor.java, ozhera-log/log-agent/src/main/java/org/apache/ozhera/log/agent/service/OutPutService.java, ozhera-log/log-api/src/main/java/org/apache/ozhera/log/api/model/meta/NodeCollInfo.java, ozhera-log/log-api/src/main/java/org/apache/ozhera/log/api/model/vo/LogCmd.java, ozhera-log/log-api/src/main/java/org/apache/ozhera/log/api/service/LogProcessCollector.java, ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/controller/MilogConfigController.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/dao/MilogLogTailDao.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/domain/LogProcess.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/LogTailService.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogProcessServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogTailServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/nacos/impl/SpaceConfigNacosPublisher.java
…ted functions
-Add getNodeCollInfo method to obtain machine collection information
-Implement the getAllAgentList method to obtain a list of all agents
-Optimize log collection configuration and distribution logic
-Refactoring some code to improve maintainability
https://github.com/apache/ozhera/issues/588
=> feat: add machine information acquisition interface and optimize related functions

ozhera-app/app-api/src/main/java/org/apache/ozhera/app/api/response/AppBaseInfo.java, ozhera-app/app-api/src/main/java/org/apache/ozhera/app/api/service/HeraAppService.java, ozhera-app/app-service/src/main/java/org/apache/ozhera/app/dao/mapper/HeraAppBaseInfoMapper.java, ozhera-app/app-service/src/main/java/org/apache/ozhera/app/service/impl/HeraAppServiceImpl.java, ozhera-app/app-service/src/main/resources/mapper/HeraAppBaseInfoMapper.xml, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/HeraAppService.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/HeraAppServiceImpl.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/LogTailServiceImpl.java
- fix the type parameter of the hera App
fix the type parameter of the hera App
None
So simple
Online
None
=> fix: fix the type parameter of the hera App

ozhera-log/log-manager/pom.xml, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/controller/MilogAiController.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/mapper/MilogAiConversationMapper.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/bo/BotQAParam.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/dto/AiAnalysisHistoryDTO.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/dto/LogAiAnalysisDTO.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/pojo/MilogAiConversationDO.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/model/vo/LogAiAnalysisResponse.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/MilogAiAnalysisService.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/bot/ContentSimplifyBot.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/bot/LogAnalysisBot.java, ozhera-log/log-manager/src/main/java/org/apache/ozhera/log/manager/service/impl/MilogAiAnalysisServiceImpl.java, ozhera-log/log-manager/src/main/resources/config.properties, ozhera-log/log-manager/src/main/resources/log.sql, ozhera-log/log-manager/src/main/resources/mapper/MilogAiConversationMapper.xml, ozhera-log/pom.xml
add the function of ai log analysis
None
The interface has been tested
Test environment verification
None
=> feat: add the function of ai log analysis
